### ISSUE TITLE
possible performance drop when in CUDA

### ISSUE THREAD

**Issue by egaburov** [jaredhoberock/agency#134]
Reproducer is below:

Master:

    $ nvcc saxpy.cu -std=c++11 -I. -run
    Measuring performance...
    SAXPY Bandwidth: 24.1978 GB/s

Last working (34793a5e0e6cf35742bf9968f1850bbac21ded28):

    $ git checkout -b working 34793a5e0e6cf35742bf9968f1850bbac21ded28
    $ nvcc saxpy.cu -std=c++11 -I. -run
    Measuring performance...
    SAXPY Bandwidth: 243.502 GB/s

Repro:

    #include <cassert>
    #include <iostream>
    #include <chrono>
    #include <agency/execution_policy.hpp>
    #include <agency/cuda/execution_policy.hpp>
    #include <thrust/device_vector.h>
    
    struct Saxpy
    {
      float a;
      const float *x, *y;
      float *z;
      __host__ __device__
      void operator()(agency::parallel_agent &self)
      {
        int i = self.index();
        z[i] = a * x[i] + y[i];
      }
    };
    
    void saxpy(size_t n, float a, const float* x, const float* y, float* z)
    {
      using namespace agency;
      bulk_invoke(cuda::par(n), Saxpy{a,x,y,z});
    }
    
    int main()
    {
      size_t n = 16 << 20;
      thrust::device_vector<float> x(n, 1), y(n, 2), z(n);
      float a = 13.;
    
      saxpy(n, a, raw_pointer_cast(x.data()), raw_pointer_cast(y.data()), raw_pointer_cast(z.data()));
    
      thrust::device_vector<float> ref(n, a * 1.f + 2.f);
      assert(ref == z);
    
      std::cout << "Measuring performance..." << std::endl;
    
      // time a number of trials
      size_t num_trials = 20;
    
      auto start = std::chrono::high_resolution_clock::now();
      for(size_t i = 0; i < num_trials; ++i)
      {
        saxpy(n, a, raw_pointer_cast(x.data()), raw_pointer_cast(y.data()), raw_pointer_cast(z.data()));
      }
      std::chrono::duration<double> elapsed = std::chrono::high_resolution_clock::now() - start;
    
      double seconds = elapsed.count() / num_trials;
      double gigabytes = double(3 * n * sizeof(float)) / (1 << 30);
      double bandwidth = gigabytes / seconds;
    
      std::cout << "SAXPY Bandwidth: " << bandwidth << " GB/s" << std::endl;
    
      return 0;
    }

**Comment by jaredhoberock** [comment]
On my system, the first bad commit is https://github.com/jaredhoberock/agency/commit/841cb088d91dfade067650dd495aae321fc151cd#diff-1d1d5778763061ebb2bdc5db696077a6

**Comment by jaredhoberock** [comment]
I believe the offending changes are the lines which call `project_index()`:

    * https://github.com/jaredhoberock/agency/commit/841cb088d91dfade067650dd495aae321fc151cd#diff-7d11234dc1d4706e6d243c67bd66562cR395
    * https://github.com/jaredhoberock/agency/commit/841cb088d91dfade067650dd495aae321fc151cd#diff-7d11234dc1d4706e6d243c67bd66562cR416

The indices produced by `project_index()` probably do not preserve contiguity, so the memory accesses are not contiguous either.
