### ISSUE TITLE
saxpy example fails with cuda_launch_kernel when built for  -arch=sm_20

### ISSUE THREAD

**Issue by egaburov** [jaredhoberock/agency#149]
repro steps:

    $ nvcc transpose.cu  -I../ -std=c++11 -expt-extended-lambda -ccbin g++-4.9  -arch=sm_20 -run
    Matrix Transpose Bandwidth: 85.2077 GB/s

    $ nvcc saxpy.cu  -I../ -std=c++11 -expt-extended-lambda -ccbin g++-4.9  -arch=sm_20 -run
    terminate called after throwing an instance of 'thrust::system::system_error'
      what():  cuda::detail::checked_launch_kernel(): CUDA error after cudaLaunch(): invalid argument
    Aborted (core dumped)

    $ nvcc saxpy.cu  -I../ -std=c++11 -expt-extended-lambda -ccbin g++-4.9  -arch=sm_30 -run
    Measuring performance...
    SAXPY Bandwidth: 243.152 GB/s

**Comment by jaredhoberock** [comment]
It looks like this fails because the grid dimension the program chooses is too large for a PTX 2.0 program. One simple workaround is to make `n` smaller.

A comprehensive fix would make the underlying executor smarter. I will file a separate issue for that.
