### ISSUE TITLE
Relationship of agency with Thrust / Parallelism TS

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/agency#51]
I've read the description, looked at examples, but honestly don't understand: what does Agency do that cannot be done with Thrust / Parallelism-TS?  Can you please elaborate?

My current, obviously incorrect, understanding is that it does basically the same thing, using slightly different syntax, described by slightly different jargon.

What can be done with `bulk_invoke` that cannot be done with `for_each_n`?
What are non-trivial differences between an execution policy and an executor(+additional state related to the parallel decomposition)?

**Comment by jaredhoberock** [comment]
> I've read the description, looked at examples, but honestly don't understand: what does Agency do that cannot be done with Thrust / Parallelism-TS? Can you please elaborate?

Agency doesn't do much of anything yet, and the unit test example programs are not meant to be pedagogical. However, Agency is intended to be an implementation layer for any algorithm found in either Thrust or the Parallelism TS. In general Agency is intended to be able to implement any parallel algorithm not easily captured by the algorithms found in the Parallelism TS. Some examples include stencil operations, matrix transposition, or graph operations.

> What can be done with bulk_invoke that cannot be done with for_each_n?

One example of something that can be done with `bulk_invoke` but not `for_each_n` is synchronization and communication between lambda invocations via shared variables. Another example is the creation of multidimensional or hierarchical iteration spaces.

> What are non-trivial differences between an execution policy and an executor(+additional state related to the parallel decomposition)?

Executors are intended to be the additional state carried by an execution policy that the policy uses to create the execution agents which actually invoke functions during parallel algorithm execution.

**Comment by andrewcorrigan** [comment]
That helps a lot.  Thanks.
